steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/broker-performance-suite:${COMMIT_SHA}',
      '-t', 'gcr.io/${PROJECT_ID}/broker-performance-suite:latest',
      '--build-arg', 'NODE_ENV=production',
      '.'
    ]
    timeout: 1200s

  # Step 2: Push both image tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/broker-performance-suite:${COMMIT_SHA}']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/broker-performance-suite:latest']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'broker-performance-suite',
      '--image', 'gcr.io/${PROJECT_ID}/broker-performance-suite:${COMMIT_SHA}',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--timeout', '300s'
    ]

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
